### ISSUE TITLE
Deploy Postgres DB in Heroku

### ISSUE THREAD

**Issue by ValentinPerret** [kazooki117/mtg-data-analysis#7]
We chose to deploy the DB on an Heroku server.
# Tasks:
- [ ] Create Heroku account
- [ ] Start an Heroku DB
- [ ] Deploy the schema structure described in #1 in the database (tables and key definitions)
